name: Build and Deploy Webpack to GitHub Pages

on:
  push:
    branches:
      - main

# jobs:
#   # Build job
#   build:
#     # Specify runner + build step
#     runs-on: ubuntu-latest
#     steps:
#       # Setup the project in a NodeJS environment
#       - name: Checkout ğŸ›ï¸
#         uses: actions/checkout@v3

#       # Run the project build command which outputs to 'dist'
#       - name: Install and Build ğŸ”§
#         run: |
#           npm ci
#           npm run build
#       # Upload the 'dist' directory to be used in the deploy job
#       - name: Upload pages artifact ğŸ“¦
#         uses: actions/upload-pages-artifact@v3
#         with:
#           path: dist/

#   # Deploy job
#   deploy:
#     # Add a dependency to the build job
#     needs: build

#     # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
#     permissions:
#       pages: write # to deploy to Pages
#       id-token: write # to verify the deployment originates from an appropriate source

#     # Deploy to the github-pages environment
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}

#     # Specify runner + deployment step
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v3


jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - name: Build static files
        id: build
        run: |
          npm ci
          npm run build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: dist/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4